[2025-07-30T01:06:09.414+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-30T01:06:09.439+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_training.execute_training manual__2025-07-30T01:06:06.472717+00:00 [queued]>
[2025-07-30T01:06:09.447+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_training.execute_training manual__2025-07-30T01:06:06.472717+00:00 [queued]>
[2025-07-30T01:06:09.448+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-30T01:06:09.458+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): execute_training> on 2025-07-30 01:06:06.472717+00:00
[2025-07-30T01:06:09.465+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=97) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-30T01:06:09.466+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection_training', 'execute_training', 'manual__2025-07-30T01:06:06.472717+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_training_dag.py', '--cfg-path', '/tmp/tmpunzw8_tt']
[2025-07-30T01:06:09.467+0000] {standard_task_runner.py:72} INFO - Started process 98 to run task
[2025-07-30T01:06:09.467+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask execute_training
[2025-07-30T01:06:09.514+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection_training.execute_training manual__2025-07-30T01:06:06.472717+00:00 [running]> on host 0be3b7d3fd6b
[2025-07-30T01:06:09.622+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kanewyp' AIRFLOW_CTX_DAG_ID='fraud_detection_training' AIRFLOW_CTX_TASK_ID='execute_training' AIRFLOW_CTX_EXECUTION_DATE='2025-07-30T01:06:06.472717+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-30T01:06:06.472717+00:00'
[2025-07-30T01:06:09.623+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-30T01:06:14.845+0000] {font_manager.py:1639} INFO - generated new fontManager
[2025-07-30T01:06:15.109+0000] {fraud_detection_training_dag.py:22} INFO - Initializing Fraud Detection Training
[2025-07-30T01:06:15.117+0000] {fraud_detection_training.py:62} INFO - Configuration loaded successfully
[2025-07-30T01:06:15.541+0000] {fraud_detection_training.py:88} INFO - Connected to MinIO. Available buckets: mlflow
[2025-07-30T01:06:16.310+0000] {fraud_detection_training.py:182} INFO - Starting model training process...
[2025-07-30T01:06:16.311+0000] {fraud_detection_training.py:104} INFO - Reading data from Kafka topic: transactions
[2025-07-30T01:06:16.368+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('13.237.143.76', 9092)]>: connecting to pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 [('13.237.143.76', 9092) IPv4]
[2025-07-30T01:06:16.405+0000] {conn.py:497} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('13.237.143.76', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-07-30T01:06:16.853+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <checking_api_versions_recv> [IPv4 ('13.237.143.76', 9092)]>: Broker version identified as 2.6
[2025-07-30T01:06:17.026+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('13.237.143.76', 9092)]>: Authenticated as KQIWVOLDBVJZDLTP via SASL / Plain
[2025-07-30T01:06:17.026+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.237.143.76', 9092)]>: Connection complete.
[2025-07-30T01:06:17.028+0000] {consumer.py:120} WARNING - group_id is None: disabling auto-commit.
[2025-07-30T01:06:17.028+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('transactions',)
[2025-07-30T01:06:17.062+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('transactions', 0)]
[2025-07-30T01:06:17.121+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=0 host=b0-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('52.64.78.177', 9092)]>: connecting to b0-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 [('52.64.78.177', 9092) IPv4]
[2025-07-30T01:06:17.171+0000] {conn.py:497} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=0 host=b0-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('52.64.78.177', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-07-30T01:06:17.369+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=0 host=b0-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('52.64.78.177', 9092)]>: Authenticated as KQIWVOLDBVJZDLTP via SASL / Plain
[2025-07-30T01:06:17.370+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=0 host=b0-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('52.64.78.177', 9092)]>: Connection complete.
[2025-07-30T01:06:17.370+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.237.143.76', 9092)]>: Closing connection. 
[2025-07-30T01:06:17.421+0000] {fetcher.py:418} INFO - Resetting offset for partition ('transactions', 0) to offset 0.
[2025-07-30T01:06:32.790+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=0 host=b0-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('52.64.78.177', 9092)]>: Closing connection. 
[2025-07-30T01:06:32.791+0000] {fetcher.py:786} INFO - Fetch to node 0 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=0 host=b0-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('52.64.78.177', 9092)]>
[2025-07-30T01:06:32.994+0000] {fraud_detection_training.py:131} INFO - Received 45898 records from Kafka with fraud rate: 0.79%
[2025-07-30T01:06:43.018+0000] {fraud_detection_training.py:261} INFO - Starting hyperparameter tuning...
[2025-07-30T01:06:43.022+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-07-30T01:17:05.030+0000] {job.py:229} INFO - Heartbeat recovered after 189.31 seconds
[2025-07-30T01:27:54.293+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:27:54.301+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:27:59.337+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:27:59.352+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:28:04.390+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:28:04.397+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:28:09.416+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:28:09.417+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:28:14.501+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:28:14.505+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:28:19.579+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:28:19.580+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:28:24.612+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:28:24.613+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:28:29.687+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:28:29.687+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:28:34.724+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:28:34.724+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:28:39.733+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:28:39.734+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:28:44.815+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:28:44.816+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:28:49.899+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:28:49.902+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:28:54.938+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:28:54.942+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:29:00.106+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:29:00.121+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:29:05.221+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:29:05.228+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:29:10.206+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:29:10.207+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:29:15.285+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:29:15.291+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:29:20.349+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:29:20.350+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:29:25.442+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:29:25.454+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:29:30.543+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:29:30.544+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:29:35.649+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:29:35.653+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:29:40.663+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:29:40.669+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:29:45.774+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:29:45.778+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:29:50.881+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:29:50.882+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:29:55.982+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:29:55.983+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:30:01.051+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:30:01.052+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:30:06.130+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:30:06.136+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:30:11.185+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:30:11.185+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:30:16.258+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:30:16.260+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:30:22.079+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:30:22.097+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:30:27.191+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:30:27.199+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:30:32.293+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:30:32.294+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:30:37.310+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:30:37.310+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:30:42.403+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:30:42.405+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:30:47.494+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:30:47.509+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:30:52.647+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:30:52.648+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:30:57.747+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:30:57.754+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:31:02.827+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:31:02.833+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:31:07.813+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:31:07.823+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:31:12.875+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:31:12.876+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:31:17.987+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:31:17.988+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:31:23.081+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:31:23.082+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:31:28.163+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:31:28.168+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:31:33.246+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:31:33.248+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:31:38.279+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:31:38.292+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:31:43.352+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:31:43.353+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:31:48.421+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:31:48.424+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:31:53.478+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:31:53.478+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:31:58.567+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:31:58.568+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:32:03.675+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:32:03.676+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:32:08.669+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:32:08.670+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:32:13.752+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:32:13.753+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:32:18.844+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:32:18.857+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:32:24.008+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:32:24.009+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:32:29.113+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:32:29.128+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:32:34.205+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:32:34.206+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:32:39.356+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:32:39.389+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:32:44.670+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:32:44.684+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:32:49.765+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:32:49.768+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:33:29.134+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 207, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 93, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 102, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 335, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-07-30T01:35:48.620+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-07-30T01:35:54.918+0000] {job.py:229} INFO - Heartbeat recovered after 185.19 seconds
[2025-07-30T01:35:54.962+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:35:54.963+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
[2025-07-30T01:36:00.058+0000] {local_task_job_runner.py:293} ERROR - The recorded hostname ec362d7b23e9 does not match this instance's hostname 0be3b7d3fd6b
[2025-07-30T01:36:00.059+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: Hostname of job runner does not match
